// Code generated by mockery v2.20.0. DO NOT EDIT.

package repository

import mock "github.com/stretchr/testify/mock"

// MockTxFunc is an autogenerated mock type for the TxFunc type
type MockTxFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: txRegistry
func (_m *MockTxFunc) Execute(txRegistry Registry) error {
	ret := _m.Called(txRegistry)

	var r0 error
	if rf, ok := ret.Get(0).(func(Registry) error); ok {
		r0 = rf(txRegistry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockTxFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockTxFunc creates a new instance of MockTxFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockTxFunc(t mockConstructorTestingTNewMockTxFunc) *MockTxFunc {
	mock := &MockTxFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
