// Code generated by mockery v2.20.0. DO NOT EDIT.

package auth

import (
	context "context"

	model "github.com/nhan1603/ReminoAssignment/api/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockController is an autogenerated mock type for the Controller type
type MockController struct {
	mock.Mock
}

// CheckAuth provides a mock function with given fields: ctx, inp
func (_m *MockController) CheckAuth(ctx context.Context, inp LoginInput) (model.User, string, error) {
	ret := _m.Called(ctx, inp)

	var r0 model.User
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, LoginInput) (model.User, string, error)); ok {
		return rf(ctx, inp)
	}
	if rf, ok := ret.Get(0).(func(context.Context, LoginInput) model.User); ok {
		r0 = rf(ctx, inp)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, LoginInput) string); ok {
		r1 = rf(ctx, inp)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, LoginInput) error); ok {
		r2 = rf(ctx, inp)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

type mockConstructorTestingTNewMockController interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockController creates a new instance of MockController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockController(t mockConstructorTestingTNewMockController) *MockController {
	mock := &MockController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
